openwdl/wdl

- README.md
e.g.:
```
wmd3c-7fd:cromwell mcovarr$ wc -l README.md 
59 README.md
```
> Fix wc command: output of old version would not have parsed as int.

- README.md
I was using cromwell-0.16.jar
The most common issue was without the declarations it would result in messages like:
```
$ java -jar cromwell-0.16.jar run hello.wdl hello.json
[2016-02-01 17:12:22,721] [info] RUN sub-command
[2016-02-01 17:12:22,726] [info]   WDL file: hello.wdl
[2016-02-01 17:12:22,726] [info]   Inputs: hello.json
[2016-02-01 17:12:22,858] [info] Slf4jLogger started
[2016-02-01 17:12:22,883] [info] SingleWorkflowRunnerActor: launching workflow
[2016-02-01 17:12:23,241] [info] Running with database db.url = jdbc:hsqldb:mem:76a7a3c4-4518-4249-8e74-1ee6df7bd650;shutdown=false;hsqldb.tx=mvcc
[2016-02-01 17:12:23,567] [info] WorkflowManagerActor submitWorkflow input id = None, effective id = 6cfab9e1-96d6-494a-8f9b-ee849ef12a1c
[2016-02-01 17:12:23,579] [info] …
```
> Fixes needed to run tutorial

- .pullapprove.yml
These guys are apparently not collaborators on this repo
> removed non-collaborators from .pullapprove.yml

- README.md
Addresses https://github.com/broadinstitute/wdl/issues/34, and:
Fixes a few wdl examples, which did not work as documented.
Fixes a few instances where output did not match with the wdl.
Added output examples where omitted.
> Corrects "inputs" command reference, which moved from Cromwell to wdltool

- scripts/README.md
- scripts/broad_dsde_workflows/README.md
- scripts/broad_dsde_workflows/generic.options.json
This PR includes a README stating the purpose of this new directory and a generic options file so we don't have to provide a separate one for each WDL.
No archive directory yet since git doesn't do empty dirs (?) but plan to make one on first update.
> New directory for supported-but-not-prod WDLs

- SPEC.md
This is an attempt to solve the problem presented [here](https://github.com/broadinstitute/cromwell/issues/375) of composing a string from a prefix string and a list of zero or more value strings.  There are definitely a lot of ways this problem might be solved and this is a concrete proposal just to get a discussion started.  😄 
Pinging @slnovak @vdauwera @knoblett @katevoss @jsotobroad @LeeTL1220 @yfarjoun
> prefix() proposal.  Closes broadinstitute/cromwell#375

- scripts/broad_dsde_workflows/ExtractSamHeadersWf_170107.inputs.json
- scripts/broad_dsde_workflows/ExtractSamHeadersWf_170107.wdl
- scripts/broad_dsde_workflows/ValidateBamsWf_170107.inputs.json
- scripts/broad_dsde_workflows/ValidateBamsWf_170107.wdl
- scripts/broad_dsde_workflows/generic.options.json
- Grab headers from a list of SAM/BAMs (with caveat and a better way to do it on GCP with gsutil)
- Validate a list of SAM/BAMs in SUMMARY mode
> WDLs for trivial bam manipulation

- scripts/broad_dsde_workflows/ConvertPairedFastQToUnmappedBamWf_170107.inputs.json
- scripts/broad_dsde_workflows/ConvertPairedFastQToUnmappedBamWf_170107.wdl
- scripts/broad_dsde_workflows/RevertBamToUnmappedRGBamsWf_170107.inputs.json
- scripts/broad_dsde_workflows/RevertBamToUnmappedRGBamsWf_170107.wdl
- scripts/broad_dsde_workflows/RevertRGBamsToPairedFastQsWf_170107.inputs.json
- scripts/broad_dsde_workflows/RevertRGBamsToPairedFastQsWf_170107.wdl
> WDLs to revert/convert between BAM, FASTQ and uBAM

- scripts/broad_dsde_workflows/GenotypeGVCFsScatterWf_170204.inputs.json
- scripts/broad_dsde_workflows/GenotypeGVCFsScatterWf_170204.wdl
- scripts/broad_dsde_workflows/HaplotypeCallerGvcfScatterWf_170204.inputs.json
- scripts/broad_dsde_workflows/HaplotypeCallerGvcfScatterWf_170204.wdl
- scripts/broad_dsde_workflows/JointDiscoveryWf_170305.inputs.json
- scripts/broad_dsde_workflows/JointDiscoveryWf_170305.wdl
- scripts/broad_dsde_workflows/VariantRecalibrationWf_170305.inputs.json
- scripts/broad_dsde_workflows/VariantRecalibrationWf_170305.wdl
Adding WDLs for various component steps of the variant calling pipeline
- HaplotypeCaller GVCF scatter-gathered across intervals
- GenotypeGVCFs scatter-gathered across intervals
- VQSR (no scatter)
- Joint discovery (GGVCFs through VQSR, no genotype refinement)
> Standalone variant calling steps + joint discovery

- SPEC.md
- grammar.hgr
Allows expressions of the form:
```
Boolean b = ...
Int memory = if b then "2GB" else "5GB"
String docker = if b then "ubuntu:latest" else "my:docker"
```
> if then else expressions

- SPEC.md
Doc changes for the upcoming Cromwell 25 release.
> Optionals methods and pair literals

- SPEC.md
replacing incorrect use of crossProduct with cross
> fixing typo in cross example

- scripts/broad_dsde_workflows/GenericPreProcessingToGVCF_170420.b37.wgs.inputs.json
- scripts/broad_dsde_workflows/GenericPreProcessingToGVCF_170420.hg38.wgs.inputs.json
- scripts/broad_dsde_workflows/GenericPreProcessingToGVCF_170420.wdl
- scripts/broad_dsde_workflows/GenericPreProcessing_170421.hg38.wgs.inputs.json
- scripts/broad_dsde_workflows/GenericPreProcessing_170421.wdl
- scripts/broad_dsde_workflows/JointDiscoveryWf_170305.inputs.json
This PR adds two WDLs:
1. A generic, stripped-down version of the Broad production / GOTC single sample pipeline (no QC steps included). Starts with unmapped bams per readgroup and ends with HaplotypeCaller GVCF generation. Inputs requirements are relaxed to be reference-agnostic (two jsons provided, for hg38 and b37) and can be applied to exomes instead of genomes by swapping out intervals files and specifying interval padding (which is important for all exome target lists but unnecessary for the Broad's WGS intervals list).
2. Same as above but without the GVCF generation, to serve as common pre-processing script for all variant discovery pipelines.
Note that the BQSR tasks have been tweaked to use all GATK3 tools instead of the more performant GATK4 tools, for benchmarking purposes.
> Generic pre-processing and GVCF generation WDLs

- runners/cromwell_on_google/README.md
- runners/cromwell_on_google/monitoring_tools/get_yaml_value.py
- runners/cromwell_on_google/monitoring_tools/monitor_wdl_pipeline.sh
- runners/cromwell_on_google/monitoring_tools/operations_util.sh
- runners/cromwell_on_google/monitoring_tools/poll.sh
- runners/cromwell_on_google/wdl_runner/Dockerfile
- runners/cromwell_on_google/wdl_runner/README.md
- runners/cromwell_on_google/wdl_runner/cromwell_driver.py
- runners/cromwell_on_google/wdl_runner/file_util.py
- runners/cromwell_on_google/wdl_runner/jes_template.conf
- runners/cromwell_on_google/wdl_runner/sys_util.py
- runners/cromwell_on_google/wdl_runner/test-wdl/basic.papi.us.options.json
- runners/cromwell_on_google/wdl_runner/test-wdl/ga4ghMd5.inputs.json
- runners/cromwell_on_google/wdl_runner/test-wdl/ga4ghMd5.wdl
- runners/cromwell_on_google/wdl_runner/wdl_outputs_util.py
- runners/cromwell_on_google/wdl_runner/wdl_pipeline.yaml
- runners/cromwell_on_google/wdl_runner/wdl_runner.py
- runners/cromwell_on_google/wdl_runner/wdl_runner.sh
This copies the code from https://github.com/googlegenomics/pipelines-api-examples/ and renames "wdl_runner" to "cromwell-on-google" to be more specific.
> Take over Google's wdl_runner

- README.md
This is a QoL change for draft spec contributors. 
When I want to see what my changes look like in the document, I click on the `Draft 3 Language Specification` link in my repo, which should link to my own local changes, rather than the `openwdl/master` version.
> relative path to current spec

- versions/draft-3/SPEC.md
**Note that the ultimate result deviated from the original**
Makes it explicit that the inability to read the entire contents from a `read_x()` function (e.g. `read_lines`) results in the failure of the calling task or workflow. 
**Original**
This was something we meant to add to the spec as part of [Cromwell #1762](https://github.com/broadinstitute/cromwell/issues/1762) and forgot, thus it's not part of the spec. Carrying it forward as-is for now.
Explanations for the amounts. 
The ones w/ explicit character counts were based on maximum valid values. 
The rest were based on what seemed "reasonable" when trying to balance "an individual is going to want this to be as large as possible" vs "a server is going to want to not read in gigantic files constantly". For `read_lines` in particular …
> Add explicit failure when read_x() functions not completely handled

- SPEC.md
This is a cleanup of this [pull request](https://github.com/openwdl/wdl/pull/153)
Currently, there is no library function to flatten an array of array of files (Array[Array[File]]). A scatter, where each task call produces an array of files, is a natural way of ending up with such a structure. In order to flatten this array, you can write a task that takes the it as an argument, and manipulate it with python code. However, this task will also download all the files, taking significant time and disk space. To work around this, you can coerce the files into strings (their paths), and manipulate the paths.
You can see an example here. The chunk_reads_join task flattens the fastq_chunks file array, which is coerced into an Array[Array[String]].
In order to avoid this circuitous …
> Array flatten function (v2)

- versions/draft-3/SPEC.md
- Makes the Types section more readable
- Removes the out of date `grammar` box
- Corrects a comment on the behavior of optionals.
- Includes the Pair type (since it's used elsewhere throughout the SPEC, it's probably worth at least mentioning it here!)
EDIT: link to this change rendered in situ: https://github.com/cjllanwarne/wdl/blob/cjl_types_fixup/versions/draft-3/SPEC.md#types
> Fixup Types section and include 'Pair's

- versions/draft-3/SPEC.md
- Removes the deprecated wildcard format
- Mentions that subworkflows must declare their outputs, just like tasks
- General tidy-up and up-to-date-ification of the outputs section
> Workflow and subworkflow outputs: clarification and tidy-up

- versions/draft-3/SPEC.md
I believe these `while` loops were a "let's fill in the details later" placeholder in the SPEC, which we never got around to filling in.
I'm happy for a similar feature to be proposed as required, but for now I think we should remove this not-fully-thought-through section.
> Remove 'while' loops from the SPEC

- versions/draft-3/SPEC.md
This was spotted while fixing up a parsing bug in the winstanley plugin.
It turns out that the parser (and WDL) has an until-now overlooked syntax for specifying keys in objects as distinct from "create as a map then coerce it to an object" which is what I suspect all existing WDLs are doing.
Here's a [link to the change](https://github.com/cjllanwarne/wdl/blob/cjl_object_literals/versions/draft-3/SPEC.md#object-literals), in place in the doc.
> Clarification of object literal syntax

- versions/draft-3/SPEC.md
Closes #128 
Change rendered in situ: https://github.com/cjllanwarne/wdl/blob/cjl_true_false_interpolation/versions/draft-3/SPEC.md#true-and-false
This updates the spec to match the hermes grammar's parsing and Cromwell's semantic interpretation
> Clarify ${true="" false="" b} command vars

- versions/draft-3/SPEC.md
Specifically, closes #116 
Since I could find no trace of the `quote` command part option in the grammar file, I'm removing it.
I can certainly see potential uses for a `quote` option, especially around formatting elements from array inputs, but I'd rather keep this PR as a clarification and let any additions come in via "new feature" PRs.
> Clarify command part options

- versions/draft-3/SPEC.md
Clarifies the set of files expected to be returned by the `glob()` function, including that it might return 0, 1, or many files in the output `Array[File]`.
> Clarify globs

- versions/draft-3/SPEC.md
This PR is just grandfathering in https://github.com/openwdl/wdl/pull/154 for draft 3.
I guess the change must have been made:
* Before the line was drawn finalizing draft 2
* After the draft3 spec had been copied
I don't think it was a deliberate omission from draft 3...?
> Don't forget flatten

- versions/draft-3/SPEC.md
As I started wiring up input-overrides in WOM, I've hit the fact that the SPEC as written says that declarations with expressions (eg `Int x = 5`) should not be evaluated as workflow inputs (implying that they wouldn't be valid entries in a user's inputs json).
I've tried to define this ability to override, and to be specific about where it would and would not be valid. 
NB: I don't think this is necessarily the final answer (I guess that people will probably want more options to overrule call input blocks, for example), but I believe this scheme as presented is internally consistent and hopefully starts up the conversation on what we want to allow to be overridden, and how easy to make that.
> Specify how overriding inputs works

- versions/draft-3/SPEC.md
Allow the `size` function to accept an array of files as input
Here's the change [in-situ](https://github.com/cjllanwarne/wdl/blob/cjl_size_of_file_array/versions/draft-3/SPEC.md#float-sizefile-string).
> Allow size() to accept Array[File]

- versions/draft-3/SPEC.md
In a previous discussion in the Cromwell github page under this issue https://github.com/broadinstitute/cromwell/issues/2283 the concept of revamping the `Object` type was brought up. 
An `Object` Is supposed to be a JSON like type, however its functionally very hard to interact with and use. Type coercions for nested members in an object are never reliable, Caching is next to impossible, and doing actions such as localizing or delocalizing files from within the object are not supported. There was a clear desire for users to have a more complex JSON like with some sort of typing which the `Object` type did not support.
Enter the `Struct`.
A struct, similar to its C counterpart, is a construct which allows users to define their own Types dynamically, directly wihtin a WDL file by combining …
> Add Struct Construct to allow for Complex types

- versions/development/SPEC.md
Feedback I've received from out in the wild was that this was a massive, massive pain point. 
Declare as part of the spec that imports which specify a relative path are relative to the location of the WDL document issuing the import statement.
> Allow for imports relative to current location

- versions/development/SPEC.md
I have attempted to make some definitions of the behaviour when different types are mixed in expressions. 
- `Int` are converted to `Float`
- `Int` and `Float` are converted to `String`
- `File` act like `String` everywhere
Many of these choices are controversial, and I have not thought through the repercussions or investigated the cromwell implementation, but I think a starting point is needed for discussion. 
I think the most important is formatting of floats. The approach I have used is that printf 'g' is used, and any more difficult requirements should call out to a real language. Maybe printf 'f' is more usable, what does cromwell do? I would be happy to make WDL even more restricted than this, but not more expressive. 
I also removed the rarer boolean operations, most languages make …
> Clarify type conversions and meanings

- runners/cromwell_on_google/monitoring_tools/monitor_wdl_pipeline.sh
Interpreting the workspace contents has several uses of sed, which
rely on extended regular expressions, namely the use of "+" for
one-or-more instances. On MacOS, we explicitly need the "-E" flag
to enable extended regular expressions.
> cromwell_on_google: Fix monitor_wdl_pipeline output on MacOS

- versions/1.0/parsers/grammar.hgr
Between draft-2 and 1.0, we stopped calling `wdl_unescape` for some reason (but the function stuck around).
This PR restores a tweaked version of it that is compatible with other 1.0 changes.
> Properly unescape strings in 1.0

- versions/development/parsers/grammar.hgr
Identical to https://github.com/openwdl/wdl/pull/253 but for `development`
> Properly unescape strings in development

- versions/development/parsers/grammar.hgr
I propose using `development` in our "in development" grammar in place of "1.1-draft", since we may want or need to use a different version number by the time we perform the next "official release".
> Switch to 'version development' from 'version 1.1-draft'

- versions/1.0/parsers/grammar.hgr
- versions/development/parsers/grammar.hgr
Fixed #239 
The PR changes probably look more dramatic than they are. What this does is:
- Move the previous "default" lexing into a new mode called 'main'
- The new 'default' lexing mode allows only whitespace, comments and the `:version` token.
- The new main mode no longer recognized the string `version` token as anything special, allowing it to be used in value names and expressions again
---
As in:
```wdl
version 1.0
workflow version_variables {
input {
String version = "hi"
}
call foo { input: version = version}
}
task foo {
input {
String version
}
command { ... }
output {
String version_out = ""
}
}
```
> [1.0/development grammar.hgr]: Allow values called 'version'

- versions/development/SPEC.md
- versions/development/parsers/grammar.hgr
Apologies for the long wait between me saying "I want to prototype this before going any further with the PR" and actually doing so.
This is an updated version of PR #173 which moves the Directory changes to the development version of the SPEC and includes the grammar changes too.
I can also link to a real, working prototype in https://github.com/broadinstitute/cromwell/pull/3980 that I'd encourage people to try out and see how this would work for real, if adopted.
> WDL Directory Type (redux)

- versions/development/SPEC.md
In my opinion, given that the SPEC has progressed a lot since August 2015, this section is more misleading than useful.
> Remove the 'state of the specification' section

- versions/development/SPEC.md
This section doesn't seem to add much other than details on how the hermes grammar implementation works.
It's also missing the `version` statement which literally appears in the very next paragraph.
> Remove 'Document' section

- versions/development/SPEC.md
de-obfuscate the description of strings. I think this is fast-trackable.
However I do not know the intended behaviour of '\n', It should probably read `any character not in set ... '<newline>' `. But are newlines really not allowed while other whitespace and strange characters are (carriage return?)
> Specify UTF-8 encoding and tidy up string definition

- versions/development/parsers/grammar.hgr
Grammar changes required for #247 ~~(except the part about WDL being a UTF-8 document)~~ EDIT: the parser seems to accept UTF-8 encoded documents - hooray! 
Demonstrated in action in https://github.com/broadinstitute/cromwell/pull/4427
* Captures escape sequences properly (previously we were missing `\"`)
* Makes escape sequences a token type rather than silently converting them.
* This should make highlighting and conversions easier.
* It also meant I didn't need to mess around in the language-specific `wdl_unescape` functions to allow the (previously unimplemented?) `\xAB` style and `U000000AB` style escape sequences.
* But engines will now need to process `escape` tokens to make the final strings.
NB: a similar change would be required in the WDL 1.0 parser if we want to make the above …
> [Hermes Grammar] Implement string escapes for #247

- versions/development/SPEC.md
- versions/draft-3/SPEC.md
Tidies up the call section, and introduces a proposed new `after` keyword to provide non-output-based dependencies
> Proposal for 'after' keyword

- versions/development/SPEC.md
So it came to my attention that we do not actually specify how comments should work. They are appropriately defined within the grammar, but the documentation around comments is pretty much non-existent. Up to now, we really have just banked on the fact that people expected the `Bash` syntax for comments and never really thought of whether there would be confused or not over this
> Clarified how comments are supposed to work

- versions/development/SPEC.md
@EvanTheB I have attempted to rebase your PR #228. In this PR I have also removed the offending example which causes issues in the other PR
@cjllanwarne  @geoffjentry can you please go over this with a fine toothed comb? The Rebase was quite ugly
> Proposal: remove object from the language - Revisit

- versions/development/parsers/grammar.hgr
To satisfy #228, and because Uri was *never* a type in the spec 🤦‍♂️
> [Hermes Grammar] Removal of Object (and Uri)

- versions/development/SPEC.md
After running into yet another case where `None` is definitely needed (or otherwise causing hideous workarounds) I decided to at it as an example in this pull request. 
This aims to implement things that were discussed in #209
> Add "None" to spec

- versions/1.0/parsers/grammar.hgr
- versions/development/parsers/grammar.hgr
Based on the [grammar in the 1.0 spec](https://github.com/openwdl/wdl/blob/master/versions/1.0/SPEC.md#call-statement), a call block like
```
call my_task {}
```
should be allowed based on the line
```
$call_body = '{' $ws* $inputs? $ws* '}'
```
On that basis I am submitting this grammar change as a bugfix rather than a spec change.
I am aware that [the spec for version `development`](https://github.com/openwdl/wdl/blob/master/versions/development/SPEC.md#call-statement) does not have an equivalent grammar example. However, nothing there seems to _disallow_ this implementation so I am submitting this change for `development` as well.
> Grammar bugfix: allow empty { } for calls in 1.0 and up

- versions/1.0/parsers/grammar.hgr
Right now, the grammar does not correctly handle strings like
```
String q1 = "leading text \" trailing text"
```
The example above is sliced up into one string `"leading text "` and three bare symbols `trailing`, `text`, `"` which is clearly wrong.
This PR fixes the issue by preventing quotes that follow the escape character `\` from marking the end of a string.
In regex terms, it adds a negative lookbehind for `\` inside the positive lookahead that stops at `"`.
> Grammar bugfix: don't stop reading a string at an escaped quote in 1.0

- versions/development/SPEC.md
~I find the mini grammar examples very helpful and I suspect this particular one may have been dropped inadvertently between 1.0 and development.~
I've learned that the grammar examples are being gradually expunged, so I rewrote as prose + example.
> Clarify empty call blocks

- versions/development/SPEC.md
Added `~{ }` commentary to the appropriate version of the SPEC.md; I am sorry for editing the wrong one last time around.
Related issue is: [https://github.com/openwdl/wdl/pull/url](url)
> `~{ }` use commentary in SPEC

- versions/development/SPEC.md
Not exciting, but we need an explicit list of keywords that can't be used as identifiers, because they'd complicate language parsing or cause ambiguities/confusion. 
Not included in this list, but debatable: `default sep version`
> add keyword list

- versions/development/SPEC.md
There are several occurrences of `Integer` in the spec which seemingly should be `Int` since that's the spec-defined type name. (Not sure if `Integer` is vestigially supported in Cromwell?)
> [trivial] standardize several occurrences of Integer to Int

- versions/development/SPEC.md
Following discussion on issue #271, this PR is a straw-man resolution to current ambiguity over how/when the optional and nonempty type quantifiers are "enforced." It will definitely need debate and discussion, so fire away!
A couple of comments to start:
* The `select_first` idiom is workable but not exactly loved; there's some discussion on #187 about nicer sugar which could follow on.
* On the other hand I don't think there's an idiomatic way to coerce `Array[T]` to `Array[T]+` right now, which is needed if we want to enforce nonempty in the same way we propose to statically validate optionals. (And it would be a little weird to enforce one of them statically and the other only at runtime, right?)
> Clarify optional and nonempty type constraints

- highlighters/emacs/README.md
Adding Emacs to the list of highlighters that makes writing WDL easier.
> Link to relevant Emacs packages for syntax highlighting and indentation

- versions/development/SPEC.md
I'm not sure if I should use `master` or `develop` as the merge-base.
> Fix a potential syntax issue with the WDL SPEC

- versions/development/SPEC.md
Some of the illustrations to code snippet examples are not matched properly. These are a few suggested fixes (thanks @geoffjentry for pointing the `WDL development version`)
> fix a few typos

- versions/development/SPEC.md
:sunglasses: 
I assume this is some vestigial typo as the spec has many such examples
> permit one-letter identifiers

- README.md
Hi all,
I thought adding pytest-workflow as a test tool on the README page might be a good move:
- Supports both MiniWDL and Cromwell
- tests are simple to make
- BioWDL is tested with this tool
Having any test framework is better than having nothing at all, and currently there are no test frameworks listed.
Disclaimer: I am the principal author of pytest-workflow. We have hammered out the YAML specs for pytest-workflow at the LUMC with four people who are heavily involved in pipeline development (including @DavyCats). 
I have not suggested this before because I do not want this to come across as self-aggrandizement. But on the other hand I feel that a test tool would be of great use to many people.
What do you think? Does pytest-workflow deserve a place on the README page?
> Add pytest-workflow as a test tool on the readme page.

- .github/PULL_REQUEST_TEMPLATE.md
- CHANGELOG.md
This implements the discussion in #344:
+ Changelog in the root.
+ Add pull request template.
I added most of the v2.0 milestone merged changes. In some cases I have excluded grammar changes because they merely implemented a thing that was already listed as a change.
The unmerged changes are not added, and should be added upon merging. Any future PR's will get a reminder to add the changes to the log.
I have added some style guides in the comment header of the changelog as well. And also a guide on what should be mentioned per change. This is of course up for debate.
> Add a changelog.

- versions/1.0/parsers/antlr4/WdlParser.g4
- versions/development/parsers/antlr4/WdlParser.g4
Thanks to @orodeh who identified this bug. The Call name in the grammar will not properly parse a call from a subworkflow ie `sub.task`, and was not able to handle the `dot` properly. 
This should fix the problem by adding a separate call_name rule
> Added call_name rule to handle calls from subworkflows

- versions/1.0/parsers/antlr4/WdlParser.g4
- versions/development/parsers/antlr4/WdlParser.g4
Thanks to @orodeh for reporting this bug. The `expressions` rule evaluation order, resulted in the inability reach inner engine function calls from within another engine function. this was due to a rule ambiguity that changing the ordering should resolve.
> Fixed expression rule evaluation order

- CHANGELOG.md
- versions/development/SPEC.md
Introduce a new engine function for adding a suffix to elements in an array. This is the natural complement to the `prefix` function.
The desire for this function came from a discussion in the [Slack Support Channel](https://openwdl.slack.com/archives/CTE06LC85/p1585891984096500), where a user wanted to add  a `"` around each element in an array of strings before passing it to the `sep` placeholder in a command
Additonally, added two convenience functions: `quote(Array[X])` and `squote(Array[X])` which work functionally similar to `suffix("'",prefix("'",x))`
> Added Suffix and similar Quoting Engine Functions

- versions/1.0/parsers/antlr4/WdlLexer.g4
Including SignedDigits in IntLiteral (and SignedFloatFragment in FloatLiteral) causes the lexer to always parse a `+` or `-` followed directly by a number as a signed literal, even in the context of expressions where the +/- should be treated as an operator. For example: `i + 5` parses fine but `i +5` does not. Just as in the Hermes grammar, `+5` should be treated as either a unary expression or the RHS of an addition, and it is up to the expression evaluator to convert a stand-alone unary operation to a signed number.
> Stop parsing signed numbers as literals

- versions/Differences.md
Beginning a document to enumerate the differences between WDL versions. This will be useful to users to help them know what they need to update to move their WDLs from one version to another, and it will be useful to those implementing parsers or workflow engines to know what new features they need to support and old features they need to deprecate.
I started by documenting the difference between Draft-2 and 1.0 as it seems like these are the two versions most often found "in the wild." Eventually we should enumerate all the differences between each successive pair of versions.
I would greatly appreciate help in answering the "Open Questions" as well as additions/changes anywhere I've missed something/gotten something wrong.
> Add document with differences between WDL versions

- .gitignore
- versions/1.0/parsers/antlr4/JavaScript/package-lock.json
- versions/1.0/parsers/antlr4/JavaScript/package.json
- versions/development/parsers/antlr4/JavaScript/package-lock.json
- versions/development/parsers/antlr4/JavaScript/package.json
Several of the Antlr4 dependencies were outdated and one (minimist) was causing some security flags to be reported by dependanbot. To fix this I simply ran `npm update` on all Grammar versions
> Update JS Grammar Dependencies

- README.md
This is a very useful utility that we use now to distribute our WDL workflows. https://github.com/biowdl/wdl-packager
Our way of distribution used to be that people needed to recursively clone our git repos. For our [biowdl germline-DNA](https://github.com/biowdl/germline-DNA) that meant recursively pulling quite a lot of repos, including all the test files. This totalled a 100 MB download. It was only useable when running cromwell on the command line and when git was available.
With this package the download on the [release page](https://github.com/biowdl/germline-DNA/releases) for the wdl file and its import package is just 555 KB. Git is not required. These files can also be used with the Cromwell API directly. For WDL runners that do not support an imports zip package, the zip package …
> Add wdl-packager to the readme

- versions/development/SPEC.md
I was working on [wdl-packager](https://github.com/biowdl/wdl-packager/) and stumbled across the implementation of the `file://` protocol. Apparently [miniwdl](https://github.com/chanzuckerberg/miniwdl) does not support relative imports with this protocol.
I made a [PR](https://github.com/chanzuckerberg/miniwdl/pull/310). @mlin did some research and find out that relative imports should not be allowed at all with this protocol.
This makes it useless for use in portable WDLs. Also [the number of slashes  is confusing](https://en.wikipedia.org/wiki/File_URI_scheme#How_many_slashes?). I have never used it in a workflow. I have never seen it used in a workflow. Since we are heading towards 2.0 now is a good moment to remove this protocol.
> remove file:// protocol

- CHANGELOG.md
- versions/1.1/SPEC.md
- versions/development/SPEC.md
It is the 1.1 spec with all deprecated items removed, and with Directory and PR #315 added in.
This will actually be easier to review if you diff it vs. the 1.1 spec rather than try to compare it to the old development spec.
> Replace development spec with updated version of 1.1 spec

- versions/development/SPEC.md
Addresses #348 reported by @yihming
> Fix hex codes for single/double quotes in spec

- versions/development/SPEC.md
The ability to have multi-line strings has been requested several times. It would also make easier several of the other proposals under consideration, such as in-line Dockerfile and evaluation of arbitrary expressions. I went with Python/Scala-style rather than HEREDOC style as that seems most idiomatic for WDL.
This is implemented in the v2 ANTLR4 grammar in a wdlTools branch: https://github.com/dnanexus-rnd/wdlTools/tree/multiline-strings/src/main/antlr4/v2
> Multi-line strings

- SPEC.md
This PR is the result of a few discussions that have been ongoing over the past while (https://github.com/openwdl/wdl/discussions/458 and https://github.com/openwdl/wdl/discussions/443) of different ways to make improve the security and usability of WDL.
This PR adds the ability to declare environment variables within the task scope, as well as to pass values for those variables within a `call` block. Most WDL engines rely on templating in values to the command section prior to command execution. While this is convenient and allows us to define our own expression language within a command block, it does mean that any WDL command is subject injection attacks or poor formatting during execution.
Using environment variables circumvents this issue by not relying on templating at all. Instead …
> Support Defining Environment Variables Within a Task
