- SPEC.md
@scottfrazer Wouldn't mind someone double checking my wording here
> Update the runtime section

- python/examples/1.wdl
- python/wdl/engine.py
- python/wdl/main.py
Here are my changes for using SGE.   (Enabled when you run "wdl run --sge file.wdl")   Feel free to take them if they're useful for anyone. 
I only made sure some simple test workflows ran successfully.  I haven't run anything large so I wouldn't be surprised to discover it may need changes to make it more robust when working with large workflows.  Conceptually, I think it should work though.
At the same time, no pressure to take these changes.  You can always wait until I have had more real-life experience using them and they might mature further later.
> Changes for enabling SGE execution

- SPEC.md
I believe this small edit makes the workflow outputs description clearer and easier to read.
> Updating the workflow outputs description

- scripts/README.md
- scripts/broad_pipelines/PublicPairedSingleSampleWf-160624.wdl
- scripts/broad_pipelines/README.md
This adds a directory structure for scripts + the two public Broad pipelines we have so far. Still need to run a few checks before merging.
Seeking comments on the directory names + how do we provide accompanying documentation and data resources for running/testing the scripts.
> Add the production WDL for the GOTC single-sample pipeline

- scripts/broad_pipelines/PublicPairedSingleSampleWf_160714.json
- scripts/broad_pipelines/PublicPairedSingleSampleWf_160714.wdl
- scripts/broad_pipelines/README.md
- scripts/broad_pipelines/archive/PublicPairedSingleSampleWf_160624.wdl
- Generate public WDL from finalized private WDL
- Replace 160624 WDL with the new WDL (move that one to the archive)
- Add JSON of example inputs with dummy filepaths (to be replaced with bucket addresses once the Verily bucket is up)
- Amend README to reflect presence of inputs JSON
> Update PairedSingleSampleWf and add JSON of inputs

- scripts/tutorials/SimpleVariantDiscovery.wdl
- scripts/tutorials/SimpleVariantSelection.wdl
- scripts/tutorials/helloHaplotypeCaller.wdl
- scripts/tutorials/jointCallingGenotypes.wdl
This pull request is for #39 
Upload the following scripts:
> Add WDL scripts from forum

- scripts/broad_pipelines/PairedSingleSampleWf_160720.md
Mirrors documentation at <https://software.broadinstitute.org/gatk/documentation/article?id=7899>.
> Add documentation for PESS pipeline

- .gitignore
- scripts/tutorials/gatk/README.md
- scripts/tutorials/gatk/tutorial_8017.json
- scripts/tutorials/gatk/tutorial_8017.wdl
- scripts/tutorials/gatk/tutorial_8017_postalt.json
- scripts/tutorials/gatk/tutorial_8017_postalt.wdl
- scripts/tutorials/gatk/tutorial_8017_toSE.json
- scripts/tutorials/gatk/tutorial_8017_toSE.wdl
- Added two new WDL scripts and matching JSONS for calling variants on alternate contigs.
- Added a README.md. This readme has a link (to Tutorial#8017) that is yet to go live but it will soon.
- Modified the original WDL script based on @vdauwera 's feedback.
Apologies if I'm committing any git offenses. I am new to this and think I may have done something funny while attempting a rebase.
> WDLs for a GATK tutorial

- SPEC.md
- grammar.hgr
Update WDL spec to reflect the workflow level metadata change.
Update grammar file forthe same (plus backfilling previous changes)
> update to include (parameter) meta

- SPEC.md
These changes will be implemented in Crowell 0.23
> Update import statement docs

- SPEC.md
@katevoss not sure how you want to include this in your refactoring, but I wanted to at least provide the content for the conditionals section.
> Documenting conditionals

- scripts/broad_dsp_workflows/format-conversion/bam-to-unmapped-readgroup-bams/0.2.0/RevertBamToUnmappedRGBams.inputs.json
- scripts/broad_dsp_workflows/format-conversion/bam-to-unmapped-readgroup-bams/0.2.0/RevertBamToUnmappedRGBams.wdl
Running tests via wdl_runner and in FireCloud
Do not merge until tests are confirmed passing.
> Updated revert-to-ubam script

- versions/draft-3/parsers/grammar.hgr
A set of updates to the hermes grammar file for draft 3.
> Draft 3 Hermes HGR update

- versions/development/SPEC.md
Hopefully fasttrackable, they were getting to me.
> Spell check

- versions/development/SPEC.md
No explanation needed, see the code ;)
> Adding keys function

- versions/development/SPEC.md
This makes it more compatible with header plugins.
> Update version statement

- versions/development/parsers/grammar.hgr
As part of the implementation for #162
> [Hermes Grammar] 'after' keyword

- versions/development/parsers/grammar.hgr
- Implementation detail for #263
> [Hermes Grammar] Add none literal

- versions/development/SPEC.md
I just noticed that this table wasn't rendering correctly.
> fix escape sequence table

- README.md
- versions/1.0/SPEC.md
- versions/development/SPEC.md
This PR enables syntax highlighting in README.md and versions/1.0/SPEC.md.
> Enable syntax highlighting

- GOVERNANCE.md
Just a bit of cleanup on some recent changes.
@orodeh @cjllanwarne can you please confirm that all of your information is correct?
> Updated Core team members

- CONTRIBUTING.md
- GOVERNANCE.md
- README.md
- RFC.md
Alright, This is the first pass cleaning up the readme.
I stripped out all of the example use cases. Frankly I consider this an upgrade and we can work on either highlighting current community howtos or just write some wiki pages instead of putting them in the main readme
> Updated RAEDME docs and removed outdated usage

- versions/development/SPEC.md
> [minor] add missing paren in read_map example

- CHANGELOG.md
- versions/development/SPEC.md
Resolve conflicts from: https://github.com/openwdl/wdl/pull/229 + added changelog per new repo checklist.
- MiniWDL (https://github.com/chanzuckerberg/miniwdl/pull/381): _merged_
- Cromwell (https://github.com/broadinstitute/cromwell/pull/5494): _awaiting review_
> Clarify string interpolator options + add sep engine function

- GOVERNANCE.md
> John Didion replacing Ohad on Governance committee obo DNAnexus

- versions/development/SPEC.md
Fixed a handful of typos in the "Acyclic Sub-Sections" and "Map[X,Array[Y]] collect_by_key(Array[Pair[X,Y]])" sections
> fixed typos

- versions/1.1/Errata.md
> Add errata for v1.1

- versions/1.1/parsers/antlr4/WdlV1_1Lexer.g4
- versions/1.1/parsers/antlr4/WdlV1_1Parser.g4
> WDL v1.1 grammar

- CHANGELOG.md
- versions/1.1/Errata.md
- versions/1.1/ImplementationGuide.md
Pulled in some missing type coercion sections from #396.
> add more errata

- versions/1.1/Errata.md
> Add incorrect example to errata

- CHANGELOG.md
- versions/1.0/parsers/antlr4/WdlV1Lexer.g4
- versions/1.1/parsers/antlr4/WdlV1_1Lexer.g4
- versions/draft-2/parsers/antlr4/WdlDraft2Lexer.g4
> BeginWhitespace lexer rule match non empty string

- CHANGELOG.md
- versions/development/SPEC.md
> fix ternary operator description

- GOVERNANCE.md
> Added new members to governance committee

- README.md
See dockstore/dockstore#5185 -- fixing here for now as it will take us longer to deploy the Dockstore fix.
> Fix link to Dockstore

- versions/1.0/SPEC.md
> Update incorrect example for pair literal section in README of version 1.0

- README.md
> Update links for DNAnexus wdl tools
